[package]
description = "Substrate mixnet"
name = "sc-mixnet"
version = "0.1.0-dev"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-mixnet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
futures = "0.3.21"
futures-timer = "3.0.2"
libp2p = "0.46.1"
log = "0.4.8"
mixnet = { git = "https://github.com/paritytech/mixnet", version = "0.1.0"}
rand = "0.7.2"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.10.0-dev", path = "../../utils/prometheus" }
ambassador = "0.3.2"

sp-application-crypto = { version = "6.0.0", path = "../../primitives/application-crypto" }
sp-api = { version = "4.0.0-dev", path = "../../primitives/api" }
sp-core = { version = "6.0.0", path = "../../primitives/core" }
sp-keystore = { version = "0.12.0", path = "../../primitives/keystore" }
sp-runtime = { version = "6.0.0", path = "../../primitives/runtime" }
sp-session = { version = "4.0.0-dev", path = "../../primitives/session" }
sp-finality-grandpa = { version = "4.0.0-dev", path = "../../primitives/finality-grandpa" } # TODO is there reexport from  sc crate?

sc-authority-discovery = { version = "0.10.0-dev", path = "../authority-discovery" }
sc-client-api = { version = "4.0.0-dev", path = "../api" }
sc-finality-grandpa = { version = "0.10.0-dev", path = "../finality-grandpa" }
sc-network = { version = "0.10.0-dev", path = "../network" }
sc-network-common = { version = "0.10.0-dev", path = "../network/common" }
sc-network-transactions = { version = "0.10.0-dev", path = "../network/transactions" }
sc-utils = { version = "4.0.0-dev", path = "../utils" }
